# Dependabot configuration for automated dependency updates and security patches
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "shawntz"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
    # Group minor and patch updates together
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Monitor GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "shawntz"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"

  # Monitor Docker base image
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "shawntz"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
